spring.application.name=resume.server

# PostgreSQL datasource (Docker container exposed on localhost:5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/webserver_db
spring.datasource.username=webuser
spring.datasource.password=webpassword

# Hibernate should NOT create/update tables in this project.
# Flyway owns schema changes; Hibernate just validates mappings.
spring.jpa.hibernate.ddl-auto=validate

# Flyway migrations
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Shows the actual SQL Hibernate runs in your console
# Great for learning - you see exactly what your java translates to
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Swagger UI will be at: http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs

# Actuator ? health endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always